title: Kevin Jané
description: Economist | Data Analyst
show_downloads: false
theme: minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minimal:
  social_links:
      - { platform: github,         user_url: "https://github.com/kevinDjane" }
      - { platform: linkedin,       user_url: "https://www.linkedin.com/in/kevinjane/" }
